site_name: Our Awesome Blog
site_description: A blogging site built with Material MKDocs
site_url: https://sitename.example
theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - search:
  - blog:
      blog_dir: .
      # archive_date_format: MM/yyyy
      # archive_url_date_format: MM/yyyy
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      # categories_allowed:
      #   - Tech
      #   - Life
      post_url_format: "{slug}"

  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@InspiredbyGrace-o7k
    - icon: fontawesome/brands/twitter
      link: https://x.com/cikguwilson

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg