authors:
  wilson:
    name: Wilson Wang
    description: Educator
    avatar: https://avatars.githubusercontent.com/u/64772208
    url: https://www.youtube.com/@InspiredbyGrace-o7k
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs